print("This file from VN7")
print("Double check")
print("git push by terminal")
print("OK")
print("which python")
print("from WSL")
print("from WSL")
print("from VS code based on WSL")
print("from VS code based on WSL")
print("git was insatll by conda in WSL, this repository was pushed by VS code based on WSL")