print("This file from VN7")
print("Double check")
print("git push by terminal")
print("OK")
print("which python")
print("from WSL")
print("from WSL")
print("from VS code based on WSL")
print("from VS code based on WSL")